title: FNU Koustubh
logo: /assets/PHOTO.jpg
description: "I am a Garduate student at the University of Maryland, college Park. My research interests are in the area of computer vision, control systems, machine learning, and robotics. I am actively searching for an internship or full time role"
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
